apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: insurance
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://user:pass@rabbitmq.insurance.svc.cluster.local:5672"
    - name: durable
      value: "true"