apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: insurance
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
            
    processors:
      k8sattributes:
        passthrough: false
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.node.name
            - k8s.container.name
            - k8s.deployment.name
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: connection
      batch:
        timeout: 5s
        send_batch_size: 1000

    exporters:
      debug:
        verbosity: detailed
        
      clickhouse:
        endpoint: tcp://otel:otelpass@clickhouse:9000?dial_timeout=10s&compress=lz4
        database: default
        traces_table_name: otel_traces
        create_schema: true
        timeout: 10s
        retry_on_failure:
          enabled: true
        
    service:
      telemetry:
        logs:
          level: debug
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, batch]
          exporters: [debug, clickhouse]
          
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.146.1
          args: ["--config=/conf/otel-collector-config.yaml"]
          ports:
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: config-volume
              mountPath: /conf
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config

---

apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: insurance
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318